### ISSUE TITLE
Error in third plot of README

### ISSUE THREAD

**Issue by kitbenjamin** [willmorrison1/daRt#2]
When running 

`simData <- daRt::getData(x = simulationDir, sF = sF)`

For the third plot in the README I get: 

```
Error in filesFun(x = x[i], sF = sF) : 
  RB3DFiles() expected at least one RB .bin file (the non-'typeNum' file) in:
 C:\Users\user\DART\user_data\simulations\cesbio/output//BAND0/RADIATIVE_BUDGET/ITER1``
```

Edit: I have not radiative_budget directory (using cesbio shipped from dart)

**Comment by willmorrison1** [comment]
Please pull the repository to your local RStudio workspace and:
-update the .RMd readme file (update file and "knit") - this file makes the readme that you see on the main github page
-clarify the error message in RB3Dfiles() function e.g. replace "RB" with "radiative budget"to give error message: "No radiative budget files found. RB3DFiles() expected at least one radiative budget .bin file (the non-'typeNum' file) in:"
